### ISSUE TITLE
[BUG] Crash with `NoClassDefFoundError` `PayloadTypeRegistry`

### ISSUE THREAD

**Issue by Azarattum** [samolego/FabricTailor#109]
## Issue
- [x] I'm not using TLauncher (it messes up the skins, also, piracy is not supported)

**Describe the bug**

After updating to 1.20.4 (from 1.20.2) FabricTailor 2.4.2 I receive the following crash message on server startup:
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fabrictailor'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.11.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[server.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/networking/v1/PayloadTypeRegistry
        at org.samo_lego.fabrictailor.FabricTailor.onInitialize(FabricTailor.java:59) ~[fabrictailor-2.4.2.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.networking.v1.PayloadTypeRegistry
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at org.samo_lego.fabrictailor.FabricTailor.onInitialize(FabricTailor.java:59) ~[fabrictailor-2.4.2.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
        ... 7 more
```

**To Reproduce**

1. Start the server
2. Observe the crash

**Logs**

Full logs here: https://mclo.gs/aAG51NF
I'm also using some server-side optimizations, full list in the logs.

Any ideas what could have caused this?

**Additional Context**

```
java --version
openjdk 22.0.1 2024-04-16
OpenJDK Runtime Environment Zulu22.30+13-CA (build 22.0.1+8)
OpenJDK 64-Bit Server VM Zulu22.30+13-CA (build 22.0.1+8, mixed mode, sharing)
```

**Comment by samolego** [comment]
Update fabric api please

**Comment by samolego** [comment]
Sure, will check it. Sorry, didn't spot that you have .4

**Comment by samolego** [comment]
Tags seem fine
![Screenshot_20240615-203412_Firefox](https://github.com/samolego/FabricTailor/assets/34912839/34a3051e-f129-4427-86a7-e733f8421a78)
